use poem_openapi::Enum;
use strum::{Display, EnumString};

/// The package ecosystem whose lock file format the manifest conforms to.
///
/// Tells the backend which parser to use when ingesting the uploaded binary.
/// Each variant maps 1-to-1 to a supported lock file format.
#[derive(Enum, Debug, Clone, Copy, PartialEq, Eq, Display, EnumString)]
pub enum ManifestType {
    /// Go module manifest generated by running `go list -m -json all | jq -s '.'`.
    Go,
    /// Rust/Cargo lock file (`Cargo.lock`).
    Cargo,
    /// Node.js npm lock file (`package-lock.json`).
    Npm,
    /// Python uv lock file (`uv.lock`).
    Uv,
    /// Python Poetry lock file (`poetry.lock`).
    Poetry,
}

impl From<ManifestType> for core_db::workspace::ManifestType {
    fn from(value: ManifestType) -> Self {
        value.to_string()
    }
}

impl From<ManifestType> for package_analyzer::ManifestType {
    fn from(value: ManifestType) -> Self {
        match value {
            ManifestType::Go => Self::Go,
            ManifestType::Cargo => Self::Cargo,
            ManifestType::Npm => Self::Npm,
            ManifestType::Uv => Self::Uv,
            ManifestType::Poetry => Self::Poetry,
        }
    }
}

impl TryFrom<core_db::workspace::ManifestType> for ManifestType {
    type Error = strum::ParseError;

    fn try_from(value: core_db::workspace::ManifestType) -> Result<Self, Self::Error> {
        value.parse()
    }
}
