//! Data types for parsing `uv.lock` files.
//!
//! A `uv.lock` file is a TOML file generated by the [uv](https://docs.astral.sh/uv/)
//! Python package manager. Each resolved package appears as a `[[package]]` array entry:
//!
//! ```toml
//! version = 1
//!
//! [[package]]
//! name = "requests"
//! version = "2.31.0"
//! source = { registry = "https://pypi.org/simple" }
//!
//! [[package]]
//! name = "my-app"
//! version = "0.1.0"
//! source = { virtual = "." }
//! ```
//!
//! [`UvLock`] deserializes this structure. Virtual packages (the workspace root and
//! workspace members) appear with `source = { virtual = "." }` and carry no meaningful
//! version for vulnerability matching; they should be skipped during analysis.

use osv_db::types::PackageName;
use semver::Version;
use serde::Deserialize;

/// A parsed `uv.lock` file.
#[derive(Debug, Clone, Deserialize)]
pub struct UvLock {
    #[serde(default, rename = "package")]
    pub packages: Vec<UvPackage>,
}

/// A single package entry in a `uv.lock` file.
#[derive(Debug, Clone, Deserialize, Hash, PartialEq, Eq)]
pub struct UvPackage {
    pub name: PackageName,
    pub version: Version,
    pub source: UvSource,
}

/// Describes where a package originates from in a `uv.lock` file.
///
/// The source is serialized as a TOML inline table with a single discriminating key,
/// for example `{ registry = "https://pypi.org/simple" }` or `{ virtual = "." }`.
#[derive(Debug, Clone, Deserialize, Hash, PartialEq, Eq)]
#[serde(untagged)]
pub enum UvSource {
    /// A package resolved from a package registry (e.g. `PyPI`).
    Registry { registry: String },
    /// A package resolved from a Git repository.
    Git { git: String },
    /// A package resolved from a local filesystem path.
    Path { path: String },
    /// A package resolved from a direct URL.
    Url { url: String },
    /// A virtual package representing the workspace root or a workspace member.
    ///
    /// Virtual packages represent the project itself rather than a third-party
    /// dependency and must be excluded from vulnerability analysis.
    Virtual {
        #[serde(rename = "virtual")]
        virtual_path: String,
    },
}
