services:
  core-db:
    build:
      context: backend/core-db
      dockerfile: Dockerfile
    volumes:
      - core-db-data:/data

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    volumes:
      - frontend-build:/app/build

  service:
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      OSV_SERVICE_CORE_DB_URL: "sqlite:///data/oppsy.db"
      OSV_SERVICE_FRONTEND_PATH: "/frontend"
      TOKIO_WORKER_THREADS: "4"
    volumes:
      - core-db-data:/data
      - frontend-build:/frontend
    depends_on:
      core-db:
        condition: service_completed_successfully
      frontend:
        condition: service_completed_successfully
    ports:
      - "8080:3030"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3030/api/v1/health/ready"]
      interval: 5m
      timeout: 5s
      retries: 3
      start_period: 5m

volumes:
  core-db-data:
  frontend-build:
