//! Generic Responses are all contained in their own modules, grouped by response codes.

use std::{
    collections::HashSet,
    hash::{Hash, Hasher},
};

use poem::{IntoResponse, http::StatusCode};
use poem_openapi::{
    ApiResponse,
    payload::Json,
    registry::{MetaResponse, MetaResponses, Registry},
};
use tracing::error;

use crate::{
    db::{CoreDb, ManifestDb, OsvDb},
    notifier::Notifier,
    resources::ResourceNotRegisteredErr,
    service::common::types::error_msg::ErrorMessage,
};

/// Default error responses
#[derive(ApiResponse)]
pub enum ErrorResponses {
    /// ## Bad Request
    ///
    /// The client has not sent valid request, could be an invalid HTTP in general or
    /// provided not correct headers, path or query arguments.
    #[oai(status = 400)]
    #[allow(dead_code)]
    BadRequest,

    /// ## Unauthorized
    ///
    /// The client has not sent valid authentication credentials for the requested
    /// resource.
    #[oai(status = 401)]
    Unauthorized(Json<ErrorMessage>),

    /// ## Forbidden
    ///
    /// The client has not sent valid authentication credentials for the requested
    /// resource.
    #[oai(status = 403)]
    Forbidden(Json<ErrorMessage>),

    /// ## URI Too Long
    ///
    /// The client sent a request with the URI is longer than the server is willing to
    /// interpret
    #[oai(status = 414)]
    #[allow(dead_code)]
    UriTooLong,

    /// ## Precondition Failed
    ///
    /// The client has not sent valid data in its request, headers, parameters or body.
    #[oai(status = 412)]
    PreconditionFailed(Json<ErrorMessage>),

    /// ## Internal Server Error.
    ///
    /// An internal server error occurred.
    ///
    /// *The contents of this response should be reported to the projects issue tracker.*
    #[oai(status = 500)]
    ServerError(Json<ErrorMessage>),

    /// ## Service Unavailable
    ///
    /// The service is not available, try again later.
    ///
    /// *This is returned when the service either has not started,
    /// or has become unavailable.*
    #[oai(status = 503)]
    ServiceUnavailable(Json<ErrorMessage>),
}

/// Combine provided responses type with the default responses under one type.
pub enum WithErrorResponses<T> {
    /// Provided responses
    With(T),
    /// Error responses
    Error(ErrorResponses),
}

/// Evaluates an expression returning `Result`, unwrapping the `Ok` value
/// or early-returning an error response via `WithErrorResponses::handle_error`.
///
/// # Example
///
/// ```rust
/// let db = try_or_return!(ManifestDb::get());
/// ```
///
/// Expands to:
///
/// ```rust
/// let db = match ManifestDb::get() {
///     Ok(val) => val,
///     Err(err) => return WithErrorResponses::handle_error(&err),
/// };
/// ```
macro_rules! try_or_return {
    ($expr:expr) => {
        match $expr {
            Ok(val) => val,
            Err(err) => return WithErrorResponses::handle_error(&err.into()),
        }
    };
}

pub(crate) use try_or_return;

impl<T> WithErrorResponses<T> {
    /// Handle a 5xx response.
    /// Returns a Server Error or a Service Unavailable response.
    pub fn handle_error(err: &anyhow::Error) -> Self {
        if err.is::<ResourceNotRegisteredErr<OsvDb>>() {
            Self::service_unavailable("OSV DB is not initialised yet", err)
        } else if err.is::<ResourceNotRegisteredErr<ManifestDb>>() {
            Self::service_unavailable("Manifest DB is not initialised yet", err)
        } else if err.is::<ResourceNotRegisteredErr<CoreDb>>() {
            Self::service_unavailable("Core DB is not initialised yet", err)
        } else if err.is::<ResourceNotRegisteredErr<Notifier>>() {
            Self::service_unavailable("Notifier is not initialised yet", err)
        } else {
            Self::internal_error(err)
        }
    }

    /// Handle a 500 internal error response.
    ///
    /// Returns a 500 Internal Error response.
    pub fn internal_error(err: &anyhow::Error) -> Self {
        error!(error=?err, "Internal Server error");
        let msg = "Internal Server Error.  Please report the issue to the service owner.";
        WithErrorResponses::Error(ErrorResponses::ServerError(Json(msg.into())))
    }

    /// Handle a 503 service unavailable error response.
    ///
    /// Returns a 503 Service unavailable Error response.
    pub fn service_unavailable<E: Into<ErrorMessage>>(
        msg: E,
        err: &anyhow::Error,
    ) -> Self {
        error!(error=?err, "Service Unavailable error");
        WithErrorResponses::Error(ErrorResponses::ServiceUnavailable(Json(msg.into())))
    }

    /// Handle a 401 unauthorized response.
    ///
    /// Returns a 401 Unauthorized response.
    /// Its OK if we actually never call this.  Required for the API.
    /// May be generated by the ingress.
    pub fn unauthorized<E: Into<ErrorMessage>>(msg: E) -> Self {
        WithErrorResponses::Error(ErrorResponses::Unauthorized(Json(msg.into())))
    }

    /// Handle a 403 forbidden response.
    ///
    /// Returns a 403 Forbidden response.
    /// Its OK if we actually never call this.  Required for the API.
    /// May be generated by the ingress.
    pub fn forbidden<E: Into<ErrorMessage>>(msg: E) -> Self {
        WithErrorResponses::Error(ErrorResponses::Forbidden(Json(msg.into())))
    }

    /// Handle a 412 precondition failed response.
    ///
    /// Returns a 412 precondition failed response.
    fn precondition_failed<E: Into<ErrorMessage>>(err: E) -> Self {
        WithErrorResponses::Error(ErrorResponses::PreconditionFailed(Json(err.into())))
    }
}

impl<T: ApiResponse> From<T> for WithErrorResponses<T> {
    fn from(val: T) -> Self {
        Self::With(val)
    }
}

impl<T: ApiResponse> ApiResponse for WithErrorResponses<T> {
    const BAD_REQUEST_HANDLER: bool = true;

    fn meta() -> MetaResponses {
        let t_meta = T::meta();
        let default_meta = ErrorResponses::meta();

        // Filter out duplicated by status codes [`FilteredByStatusCodeResponse`] response
        // definitions. Priority has [`ErrorResponses`]
        let mut responses = HashSet::new();
        responses.extend(
            t_meta
                .responses
                .into_iter()
                .map(FilteredByStatusCodeResponse),
        );
        responses.extend(
            default_meta
                .responses
                .into_iter()
                .map(FilteredByStatusCodeResponse),
        );
        MetaResponses {
            responses: responses.into_iter().map(|v| v.0).collect(),
        }
    }

    fn register(registry: &mut Registry) {
        ErrorResponses::register(registry);
        T::register(registry);
    }

    fn from_parse_request_error(err: poem::Error) -> Self {
        if err.status() == StatusCode::UNAUTHORIZED {
            WithErrorResponses::unauthorized(err.to_string())
        } else if err.status() == StatusCode::FORBIDDEN {
            WithErrorResponses::forbidden(err.to_string())
        } else {
            WithErrorResponses::precondition_failed(err)
        }
    }
}

impl<T: IntoResponse + Send> IntoResponse for WithErrorResponses<T> {
    fn into_response(self) -> poem::Response {
        match self {
            Self::With(t) => t.into_response(),
            Self::Error(default) => {
                let mut response = default.into_response();
                if response.status() == StatusCode::SERVICE_UNAVAILABLE {
                    response.headers_mut().insert(
                        poem::http::header::RETRY_AFTER,
                        poem::http::HeaderValue::from_static("5"),
                    );
                }
                response
            },
        }
    }
}

/// [`FilteredByStatusCodeResponse`] is used to filter out duplicate responses by status
/// code.
struct FilteredByStatusCodeResponse(MetaResponse);
impl PartialEq for FilteredByStatusCodeResponse {
    fn eq(
        &self,
        other: &Self,
    ) -> bool {
        self.0.status.eq(&other.0.status)
    }
}
impl Eq for FilteredByStatusCodeResponse {}
impl Hash for FilteredByStatusCodeResponse {
    fn hash<H: Hasher>(
        &self,
        state: &mut H,
    ) {
        self.0.status.hash(state);
    }
}
