//! Data types for parsing `poetry.lock` files.
//!
//! A `poetry.lock` file is a TOML file generated by [Poetry](https://python-poetry.org/).
//! Each resolved package appears as a `[[package]]` array entry:
//!
//! ```toml
//! [[package]]
//! name = "requests"
//! version = "2.31.0"
//! description = "Python HTTP for Humans."
//! optional = false
//! python-versions = ">=3.7"
//! files = []
//!
//! [metadata]
//! lock-version = "2.0"
//! python-versions = "^3.12"
//! content-hash = "..."
//! ```
//!
//! Non-registry packages (git, url, directory, file) carry an optional
//! `[package.source]` subtable. Registry packages have no source entry.

use osv_db::types::PackageName;
use semver::Version;
use serde::Deserialize;

/// A parsed `poetry.lock` file.
#[derive(Debug, Clone, Deserialize)]
pub struct PoetryLock {
    #[serde(default, rename = "package")]
    pub packages: Vec<PoetryPackage>,
}

/// A single package entry in a `poetry.lock` file.
#[derive(Debug, Clone, Deserialize, Hash, PartialEq, Eq)]
pub struct PoetryPackage {
    pub name: PackageName,
    pub version: Version,
}
