//! CSRF state token wrapper for the `OAuth2` sign-in flow.

use std::{borrow::Cow, hash::Hash};

use oauth2::CsrfToken;
use poem_openapi::{
    registry::{MetaSchema, MetaSchemaRef, Registry},
    types::{ParseError, ParseFromParameter, Type},
};

/// The `state` parameter of an `OAuth2` authorization request, as defined in
/// [RFC 6749 Appendix A.5](https://datatracker.ietf.org/doc/html/rfc6749#appendix-A.5).
///
/// Generated by the client during authorization initiation and echoed back
/// verbatim by the provider in the callback, allowing the client to verify
/// that the response corresponds to a request it originated (CSRF protection).
///
/// Wraps [`CsrfToken`] with value-based equality so two tokens carrying the
/// same secret string compare as equal — necessary for looking up and
/// validating the pending state entry during the callback phase.
#[derive(Debug, Clone)]
pub struct OAuthStateId(CsrfToken);

impl From<CsrfToken> for OAuthStateId {
    fn from(value: CsrfToken) -> Self {
        Self(value)
    }
}

impl Hash for OAuthStateId {
    fn hash<H: std::hash::Hasher>(
        &self,
        state: &mut H,
    ) {
        self.0.secret().hash(state);
    }
}

impl PartialEq for OAuthStateId {
    fn eq(
        &self,
        other: &Self,
    ) -> bool {
        self.0.secret().eq(other.0.secret())
    }
}

impl Eq for OAuthStateId {}

impl Type for OAuthStateId {
    type RawElementValueType = Self;
    type RawValueType = Self;

    const IS_REQUIRED: bool = true;

    fn name() -> Cow<'static, str> {
        "string".into()
    }

    fn schema_ref() -> MetaSchemaRef {
        MetaSchemaRef::Inline(Box::new(MetaSchema::new("string")))
    }

    fn register(_registry: &mut Registry) {}

    fn as_raw_value(&self) -> Option<&Self::RawValueType> {
        Some(self)
    }

    fn raw_element_iter<'a>(
        &'a self
    ) -> Box<dyn Iterator<Item = &'a Self::RawElementValueType> + 'a> {
        Box::new(std::iter::once(self))
    }
}

impl ParseFromParameter for OAuthStateId {
    fn parse_from_parameter(value: &str) -> poem_openapi::types::ParseResult<Self> {
        if value.is_empty() {
            return Err(ParseError::custom("OAuth2 state must not be empty"));
        }
        Ok(Self(CsrfToken::new(value.to_owned())))
    }
}
